name: Bug Report
description: File a report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 1. Link to a repository that reproduces the bug
      description: |
        The best way for us to help you is if you can provide a small repository that reproduces the bug.
      placeholder: https://github.com/...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code blocks.
      render: shell
